### ISSUE TITLE
Picking up guns kicks player from server

### ISSUE THREAD

**Issue by sigurd4** [sigurd4/BioShockMod#4]
on servers, picking up a gun kicks the user. (Not from a chest etc, but say you die and have a gun in your inv, going to pick it up will kick the person picking said gun up from the server)

**Comment by sigurd4** [comment]
log:

```
26.05 07:06:44 [Server] INFO [07:06:44] [Server thread/INFO]: sullos left the game 
26.05 07:06:44 [Disconnect] User [07:06:44] 
[Server thread/INFO]: sullos has disconnected, reason: 
TextComponent{text='Internal server error', siblings=[], 
style=Style{hasParent=false, color=null, bold=null, italic=null, 
underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}} 
26.05 07:06:44 [Server] INFO ... 10 more 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) ~[yz.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) ~[sv.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:600) ~[yz.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:609) ~[yz.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:390) ~[xk.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:565) ~[FMLCommonHandler.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_323_BioshockEventHandlerFML_itemPickupEvent_ItemPickupEvent.invoke(.dynamic)
~[?:?] 
26.05 07:06:44 [Server] INFO at com.sigurd4.Bioshock.eventhandler.BioshockEventHandlerFML.itemPickupEvent(BioshockEventHandlerFML.java:109) 
~[BioshockEventHandlerFML.class:?] 
26.05 07:06:44 [Server] INFO Caused 
by: java.lang.NoSuchMethodError: com.sigurd4.Bioshock.items.ItemWeaponRanged.playPickupSound(Lnet/minecraft/entity/player/Entit    yPlayer;Lnet/minecraft/item/ItemStack;)V
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[jd.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?] 
26.05 07:06:44 [Server] INFO net.minecraft.util.ReportedException: Ticking player 
26.05 07:06:44 [Server] INFO [07:06:44] [Server thread/WARN]: Failed to handle packet for /124.176.105.107:53144 
26.05 07:06:44 [Server] INFO [07:06:44] 
[Server thread/ERROR] [FML]: 4: ASM: 
powercrystals.minefactoryreloaded.net.ConnectionHandler@730dc6d0 
onItemPickUp(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemPickupEvent;)V 
26.05 07:06:44 [Server] INFO [07:06:44] 
[Server thread/ERROR] [FML]: 3: ASM: 
com.pahimar.ee3.handler.ItemEventHandler@72ef2aa7 
onItemPickupEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemPickupEvent;)V 
26.05 07:06:44 [Server] INFO [07:06:44] 
[Server thread/ERROR] [FML]: 2: ASM: 
com.sigurd4.Bioshock.eventhandler.BioshockEventHandlerFML@4ea1675a 
itemPickupEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemPickupEvent;)V 
26.05 07:06:44 [Server] INFO [07:06:44] 
[Server thread/ERROR] [FML]: 1: ASM: 
vazkii.botania.common.achievement.AchievementTriggerer@3e7a19a9 
onItemPickedUp(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemPickupEvent;)V 
26.05 07:06:44 [Server] INFO [07:06:44] [Server thread/ERROR] [FML]: 0: NORMAL 
26.05 07:06:44 [Server] INFO [07:06:44] [Server thread/ERROR] [FML]: Index: 2 Listeners: 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) [jd.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) [mw.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288) [yz.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611) [sv.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:600) [yz.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:609) [yz.class:?] 
26.05 07:06:44 [Server] INFO at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:390) [xk.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:565) [FMLCommonHandler.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?] 
26.05 07:06:44 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_323_BioshockEventHandlerFML_itemPickupEvent_ItemPickupEvent.invoke(.dynamic)
~[?:?] 
26.05 07:06:44 [Server] INFO at com.sigurd4.Bioshock.eventhandler.BioshockEventHandlerFML.itemPickupEvent(BioshockEventHandlerFML.java:109) 
~[BioshockEventHandlerFML.class:?] 
26.05 07:06:44 [Server] INFO java.lang.NoSuchMethodError: com.sigurd4.Bioshock.items.ItemWeaponRanged.playPickupSound(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/item/ItemStack;)V
26.05 07:06:44 [Server] INFO [07:06:44] 
[Server thread/ERROR] [FML]: Exception caught during firing event 
cpw.mods.fml.common.gameevent.PlayerEvent$ItemPickupEvent@1bc53a00: 
26.05 07:06:22 [07:06:22] [Server thread/INFO]: sullos ran command Message of the Day
```
